services:
  backend:
    build: .
    ports:
      - "8124:8080" # map container port 3000 -> host port 8124   # API
        #- "8125:8080" # map container port 3000 -> host port 8125   # playground
    networks:
      - learngraphnet
    environment:
      DGRAPH_DN: "arangodb"
  arangodb:
    image: arangodb:latest
    environment: # TODO(prod): find different password init option, that does not dump it in the logs
      ARANGO_RANDOM_ROOT_PASSWORD: 1
    ports: # TODO(prod): remove - it should be debugging only
      - 8529:8529
    volumes:
      - ./docker-data/arangodb_data_container:/var/lib/arangodb3
      - ./docker-data/arangodb_apps_data_container:/var/lib/arangodb3-apps
networks:
  learngraphnet:
    name: learngraphnet
    external: true
