services:
  backend:
    build: ./docker-compose/wgo/
    command: ["wgo", "run", "-file=.go", "-xfile=_test.go", "main.go"]
    working_dir: /src
    ports:
      - "8124:8080" # host:container
    networks:
      - learngraphnet
    environment:
      DB_POSTGRES_HOST: "postgres"
      DB_POSTGRES_PASSWORD: example
      PRODUCTION: "false"
    volumes:
      - ./:/src
      - ./docker-data/_go-dev-cache/build:/root/.cache/go-build
      - ./docker-data/_go-dev-cache/mod:/go/pkg/mod
    depends_on:
      - postgres
  postgres:
    image: postgres:16.1
    networks:
      - learngraphnet
    environment:
      POSTGRES_USER: learngraph
      POSTGRES_PASSWORD: example
    volumes:
      - ./docker-data/postgres_data:/var/lib/postgresql/data
  #postgresadminer:
  #  image: adminer
  #  ports:
  #    - 8888:8080
networks:
  learngraphnet:
    name: learngraphnet
    external: true
