services:
  backend:
    build: .
    ports:
      - "8124:8080" # map container port 8080 -> host port 8124
    networks:
      - learngraphnet
    environment:
      DGRAPH_DN: "arangodb"
    volumes:
      - ./docker-data/arangodb_secrets:/secrets
    depends_on:
      - arangodb
  arangodb:
    image: arangodb:latest
    environment: # TODO(prod): find different password init option, that does not dump it in the logs
      ARANGO_RANDOM_ROOT_PASSWORD: 1
    ports: # TODO(prod): remove - it should be debugging only
      - 8529:8529
    volumes:
      - ./docker-data/arangodb_data_container:/var/lib/arangodb3
      - ./docker-data/arangodb_apps_data_container:/var/lib/arangodb3-apps
      - ./docker-data/arangodb_secrets:/secrets
    depends_on:
      - arangodb_setup
    command: ["arangod", "--server.jwt-secret-keyfile", "/secrets/jwtSecret"]
    networks:
      - learngraphnet
  arangodb_setup: # ensure setup is completed before db starts
    image: arangodb:latest
    restart: "no"
    command: ["exit", "0"]
    depends_on:
      - arangodb_setup_2
  arangodb_setup_2:
    image: arangodb:latest
    restart: "no"
    volumes:
      - ./docker-data/arangodb_secrets:/secrets
    command: ["arangodb", "create", "jwt-secret", "--secret=/secrets/jwtSecret"]
networks:
  learngraphnet:
    name: learngraphnet
    external: true
