services:
  backend:
    image: golang:1.19
    command: ["go", "run", "main.go"]
    working_dir: /src
    ports:
      - "8124:8080" # map container port 8080 -> host port 8124
    networks:
      - learngraphnet
    environment:
      DB_POSTGRES_HOST: "postgres"
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      PRODUCTION: "false"
    volumes:
      - ./:/src
      - ./docker-data/_go-dev-cache/build:/root/.cache/go-build
      - ./docker-data/_go-dev-cache/mod:/go/pkg/mod
    depends_on:
      - postgres
  postgres:
    image: postgres:16.1
    networks:
      - learngraphnet
    environment:
      POSTGRES_USER: learngraph
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - ./docker-data/postgres_data:/var/lib/postgresql/data
networks:
  learngraphnet:
    name: learngraphnet
    external: true
