// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/suxatcode/learn-graph-poc-backend/layout (interfaces: Layouter)

// Package layout is a generated GoMock package.
package layout

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/suxatcode/learn-graph-poc-backend/graph/model"
)

// MockLayouter is a mock of Layouter interface.
type MockLayouter struct {
	ctrl     *gomock.Controller
	recorder *MockLayouterMockRecorder
}

// MockLayouterMockRecorder is the mock recorder for MockLayouter.
type MockLayouterMockRecorder struct {
	mock *MockLayouter
}

// NewMockLayouter creates a new mock instance.
func NewMockLayouter(ctrl *gomock.Controller) *MockLayouter {
	mock := &MockLayouter{ctrl: ctrl}
	mock.recorder = &MockLayouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLayouter) EXPECT() *MockLayouterMockRecorder {
	return m.recorder
}

// GetNodePositions mocks base method.
func (m *MockLayouter) GetNodePositions(arg0 context.Context, arg1 *model.Graph) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetNodePositions", arg0, arg1)
}

// GetNodePositions indicates an expected call of GetNodePositions.
func (mr *MockLayouterMockRecorder) GetNodePositions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodePositions", reflect.TypeOf((*MockLayouter)(nil).GetNodePositions), arg0, arg1)
}

// ReloadForce mocks base method.
func (m *MockLayouter) ReloadForce(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReloadForce", arg0)
}

// ReloadForce indicates an expected call of ReloadForce.
func (mr *MockLayouterMockRecorder) ReloadForce(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadForce", reflect.TypeOf((*MockLayouter)(nil).ReloadForce), arg0)
}
