services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 8529:8529
    volumes:
      - ../docker-data/arangodb_data_container:/var/lib/arangodb3
      - ../docker-data/arangodb_apps_data_container:/var/lib/arangodb3-apps
      - ../test/data:/secrets
    command: ["arangod", "--server.jwt-secret-keyfile", "/secrets/jwtSecret"]
