// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateEntityResult struct {
	ID     string  `json:"ID"`
	Status *Status `json:"Status,omitempty"`
}

type CreateUserResult struct {
	Login *LoginResult `json:"login"`
}

type Edge struct {
	ID     string  `json:"id"`
	From   string  `json:"from"`
	To     string  `json:"to"`
	Weight float64 `json:"weight"`
}

type EdgeEdit struct {
	Username  string       `json:"username"`
	Type      EdgeEditType `json:"type"`
	UpdatedAt time.Time    `json:"updatedAt"`
	Weight    float64      `json:"weight"`
}

type Graph struct {
	Nodes []*Node `json:"nodes,omitempty"`
	Edges []*Edge `json:"edges,omitempty"`
}

type LoginAuthentication struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResult struct {
	Success  bool    `json:"success"`
	Token    string  `json:"token"`
	UserID   string  `json:"userID"`
	UserName string  `json:"userName"`
	Message  *string `json:"message,omitempty"`
}

type Mutation struct {
}

type Node struct {
	ID          string  `json:"id"`
	Description string  `json:"description"`
	Resources   *string `json:"resources,omitempty"`
	Position    *Vector `json:"position,omitempty"`
}

type NodeEdit struct {
	Username       string       `json:"username"`
	Type           NodeEditType `json:"type"`
	NewDescription string       `json:"newDescription"`
	NewResources   *string      `json:"newResources,omitempty"`
	UpdatedAt      time.Time    `json:"updatedAt"`
}

type Query struct {
}

type Status struct {
	Message string `json:"Message"`
}

type Text struct {
	Translations []*Translation `json:"translations"`
}

type Translation struct {
	Language string `json:"language"`
	Content  string `json:"content"`
}

type Vector struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

type EdgeEditType string

const (
	EdgeEditTypeCreate EdgeEditType = "create"
	EdgeEditTypeEdit   EdgeEditType = "edit"
)

var AllEdgeEditType = []EdgeEditType{
	EdgeEditTypeCreate,
	EdgeEditTypeEdit,
}

func (e EdgeEditType) IsValid() bool {
	switch e {
	case EdgeEditTypeCreate, EdgeEditTypeEdit:
		return true
	}
	return false
}

func (e EdgeEditType) String() string {
	return string(e)
}

func (e *EdgeEditType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EdgeEditType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EdgeEditType", str)
	}
	return nil
}

func (e EdgeEditType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NodeEditType string

const (
	NodeEditTypeCreate NodeEditType = "create"
	NodeEditTypeEdit   NodeEditType = "edit"
)

var AllNodeEditType = []NodeEditType{
	NodeEditTypeCreate,
	NodeEditTypeEdit,
}

func (e NodeEditType) IsValid() bool {
	switch e {
	case NodeEditTypeCreate, NodeEditTypeEdit:
		return true
	}
	return false
}

func (e NodeEditType) String() string {
	return string(e)
}

func (e *NodeEditType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeEditType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeEditType", str)
	}
	return nil
}

func (e NodeEditType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
